### ISSUE TITLE
After closing and reopening the app the person is no longer displayed in the seating plan

### ISSUE THREAD

**Issue by JonasDann** [BigDaddy-Germany/EduMon#107]

**Comment by mdoerfler** [comment]
I think the resumption of a lecture was knowingly deactivated by @n2code, wasn't it?

**Comment by n2code** [comment]
yes, see #43 (which by the way I can no longer care about)
@JonasDann I thought you were talking about a logged out person not being able to log in and subsequently be shown on the plan?

**Comment by mdoerfler** [comment]
Duplicated.

**Comment by JonasDann** [comment]
Yes I was talking about a person not being shown when they log in again after closing the client and students being shown in the plan even if the are rejected because their name was previously taken

**Comment by JonasDann** [comment]
Maybe it now works. It has to be tested

**Comment by mdoerfler** [comment]
Should work now. @JonasDann?
