### ISSUE TITLE
Restoration improvements

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/EduMon#129]
- [x] Interaction play button <-> open "do you want to restore?"-dialog
- [x] immediate timeline update
- [x] remember pult-up timer
- [x] :warning: **persist prefs all the time but currentLecture only, when lecture is started -> this implies that we should store `(prefs - lecture)` and `lecture` in different storage containers**

**Comment by n2code** [comment]
removed bonus because some points are actually too important and can break too much if not addressed

**Comment by mdoerfler** [comment]
Completet 4th point

**Comment by n2code** [comment]
play button already done in 1b845b794a32d4b2f2ceacef3632c9b3d0def3c6
