### ISSUE TITLE
Wheel doesn't show segments anymore

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/EduMon#150]
The wheel only shows "No segments, yet", although the lecture is startet and the course contains five members.

**Comment by n2code** [comment]
got it in Firefox 37 as well:
`uncaught exception: target must be a window!`

**Comment by pschichtel** [comment]
any special settings set in your browser ? could you (both) paste a the output of ```typeof target``` ?

**Comment by n2code** [comment]
see instant messaging, `target` is a `Window` but `typeof target === "object"`

**Comment by pschichtel** [comment]
Can be tested and closed if working

**Comment by n2code** [comment]
just encountered it again, in Firefox:
![unbenannt](https://cloud.githubusercontent.com/assets/5720936/7334346/6d728fec-eb90-11e4-85fc-fd9531d236b9.PNG)
