### ISSUE TITLE
Author tags & comments

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/EduMon#160]
pretty much self-explanatory...
since our surnames are unique in our team, they should suffice
@BigDaddy-Germany/owners

**Comment by mdoerfler** [comment]
Whole classes or each method/function?

**Comment by n2code** [comment]
I'd say whole class if it's by you or the same group, otherwise per function
-- 
Sent from my smartphone :)

Am 13. Mai 2015 00:26:33 MESZ, schrieb mdoerfler <notifications@github.com>:

**Comment by n2code** [comment]
last remaining added in 9628e02991c01e3ea41cf3674bc9f20a4ae07c85
