### ISSUE TITLE
Change type of type in message from Integer to String

### ISSUE THREAD

**Issue by JonasDann** [BigDaddy-Germany/EduMon#40]

**Comment by n2code** [comment]
that affected me as well...

**Comment by mdoerfler** [comment]
@JonasDann @n2code please agree on a solution and open new issue.

**Comment by n2code** [comment]
didn't reopen because I already fixed it... just wanted to let you know that protocol changes usually affect more than one party :wink: 

...although I'm intrigued to know why we need strings here...?

**Comment by mdoerfler** [comment]
@JonasDann ?

**Comment by JonasDann** [comment]
We needed them but now we don't need them anymore. Still will keep them for sanity.
