### ISSUE TITLE
Persist packages a.k.a. restore app state

### ISSUE THREAD

**Issue by mdoerfler** [BigDaddy-Germany/EduMon#43]

**Comment by n2code** [comment]
see #69 as well

**Comment by n2code** [comment]
I'm too busy with GUI so I have to give this to someone else...
see the changes EduMon.js in 1536783d5ff345772cc2125785247602e3f052fe for everything that has to do with it

**Comment by mdoerfler** [comment]
Seating plan should now be restored after 75211aa27f2c2445

**Comment by mdoerfler** [comment]
@JonasDann does it work fine for you?

**Comment by n2code** [comment]
**Idea: restore `EduMon.Prefs` but reset `EduMon.Prefs.currentLecture` and wait with restoring that sub branch until positive answer was given**
*warning: modules rely on a proper currentLecture, `EduMon.Prefs.currentLecture = {};` is probably not an option*
