### ISSUE TITLE
window is not defined (EduMon.Util)

### ISSUE THREAD

**Issue by n2code** [BigDaddy-Germany/EduMon#89]
![unbenannt](https://cloud.githubusercontent.com/assets/5720936/7115328/f401cd28-e1e7-11e4-96b1-dfbb1ba6e80e.PNG)

**Comment by n2code** [comment]
something something time of execution ...?

**Comment by pschichtel** [comment]
is it in the worker context?

**Comment by n2code** [comment]
nope, main app (see log) and I have no idea why
